name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 1001:5432  # Подключаем порт 5432 контейнера на 1001 порту хоста
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: qwe
          POSTGRES_DB: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set permissions for Gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build and run tests with Gradle
        run: ./gradlew build test

      - name: Deploy application (run in background)
        run: |
          nohup java -jar build/libs/socks-backspark.jar > app.log 2>&1 &
          sleep 120  # Увеличиваем время ожидания

      - name: Wait for application to start
        run: |
          for i in {1..10}; do
            curl -f http://localhost:8888 && break || sleep 10
          done

      - name: Check application logs
        run: tail -n 10 app.log

      - name: Test the deployed application
        run: curl -f http://localhost:8888 || exit 1  # Проверяем доступность приложения на порту 8888





