name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set permissions for Gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: Run tests
        run: ./gradlew test

      - name: Static code analysis (Checkstyle)
        run: ./gradlew check

      - name: Build JAR file
        run: ./gradlew bootJar

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: socks-service-jar
          path: build/libs/*.jar

      - name: Build Docker image
        run: |
          # Создаём Docker образ
          docker build -t my-app .

      - name: Push Docker image to Docker Hub
        run: |
          # Логинимся в Docker Hub
          echo ${{ secrets.DOCKER_USERNAME }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag my-app nikitkamzgb/socks-backspark-iso:latest
          docker push nikitkamzgb/socks-backspark-iso:latest

      - name: Deploy to Docker container
        if: success()
        run: |
          # Останавливаем старый контейнер, если он существует
          docker stop socks-service-container || true
          docker rm socks-service-container || true
          
          # Запускаем новый контейнер с последним образом
          docker run -d -p 8889:8888 --name socks-service-container --link socks-db nikitkamzgb/socks-backspark-iso:latest

      - name: Clean up Docker images
        run: |
          # Очищаем старые Docker образы
          docker rmi my-app || true
          docker rmi nikitkamzgb/socks-backspark-iso:latest || true





